### ISSUE TITLE
Scroll axis locking

### ISSUE THREAD

**Issue by shockey** [mathieudutour/scroll-through-time#10]
Is it feasible to lock the scrolling onto the axis that it started on, i.e. ignore X axis scrolling when a Y scroll is in progress, and vice versa?

I just installed this, and I love it, but I'm paranoid about inadvertently undoing/redoing a change when cruising through a file.

**Comment by mathieudutour** [comment]
pretty sure I already do this: https://github.com/mathieudutour/scroll-through-time/blob/master/lib/scroll-through-time.js#L12-L14

**Comment by Dylan-WY** [comment]
I think that when this function is enabled, it should be pressing a hot key to trigger the effect later.
