### ISSUE TITLE
Add a hotkey to enable time scrolling

### ISSUE THREAD

**Issue by bensteers** [mathieudutour/scroll-through-time#11]
I am kind of in love with this package, but it has some usability issues. It would be incredibly useful there was a setting to enable a hotkey that enables time scrolling if, for example, cmd is held down while scrolling and have normal behavior otherwise (you could have another setting that inverts that behavior too I suppose). 

Also, it's mentioned in #5, but scrolling still does happen when the plugin is enabled which does make it less pleasant to use.

**Comment by mathieudutour** [comment]
fixed in 0.3.0 :tada:
