### ISSUE TITLE
inverse scrolling not working

### ISSUE THREAD

**Issue by carukwbe** [mathieudutour/scroll-through-time#16]
In my installation nothing happens if I change the scrolling to the inverse. Changes between horizontal and vertical are working.

**Comment by wiccawill420** [comment]
Same here. Version 0.3.0
'Left to undo' and 'right to undo' both only undo on scroll to right for me
'up to undo' and 'down to undo' both only undo on scroll up

**Comment by mathieudutour** [comment]
should be fixed in 0.3.1
