### ISSUE TITLE
Add support for keyboard modifier

### ISSUE THREAD

**Issue by Swoy** [mathieudutour/scroll-through-time#4]
Hello, could you maybe add support for ctrlKey, altKey, shiftKey or so?

**Comment by TimMikeladze** [comment]
I'd love to see this implemented as well. It would be especially useful when you want to scroll horizontally in your text editor (for example when a line is too long) without scrolling through time.

@mathieudutour If this is something you're interested in having in this package I'll gladly send a PR, let me know.

**Comment by mathieudutour** [comment]
yep, happy to accept a PR. The modifier key could be an option

**Comment by TimMikeladze** [comment]
Great - I'll whip something up over the weekend.

**Comment by derekjobst** [comment]
Anyone still working on this?

**Comment by mathieudutour** [comment]
probably not, feel free to grab it

**Comment by mathieudutour** [comment]
fixed in 0.3.0 :tada:
