### ISSUE TITLE
Turning off autotoggle doesn't work

### ISSUE THREAD

**Issue by linky00** [mathieudutour/scroll-through-time#6]
When I start up Atom, even if I turn off autotoggle, it still runs at startup. What's weirder is that if I toggle it once, it still runs, but then if i toggle it a second time, it turns off. This makes me think that, whilst it is changing the boolean, it doesn't check that boolean's value at startup. Thanks!

**Comment by mallardduck** [comment]
@linky00 Is this issue still present? The best I can tell this shouldn't be happening since it does properly check the state/config on load.

**Comment by mathieudutour** [comment]
fixed in 0.3.0 :tada:
