### ISSUE TITLE
Scrolling inside tree panel keep package activated

### ISSUE THREAD

**Issue by orsileonel** [mathieudutour/scroll-through-time#9]
First let me thank you for this awesome package, really like using it! Lately I been having an issue, when I have a project with long file names sometimes I need to scroll horizontally to see them inside the directory panel and the scroll-through-time will activate undoing/redoing changes on the open file, is it possible to add a fix so that it only executes when you do the two fingers scroll inside the coding panel only or adding an option of holding a key while scrolling?

I'm using Atom 1.19.0 and the latest version of the scroll-through-time package.

Thank you and please let me know if you need any other information!

**Comment by mathieudutour** [comment]
probably possible yes. I'm a bit stretch right now but happy to accept a PR

**Comment by orsileonel** [comment]
Thanks for the quick reply @mathieudutour! Don't worry and keep the awesome work up! 😃

**Comment by mathieudutour** [comment]
fixed in 0.3.0 :tada:
